apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
  selector:
    app: fastapi-agent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-agent
  template:
    metadata:
      labels:
        app: fastapi-agent
    spec:
      containers:
        - name: agent-app
          image: fastapi-agent:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_DB
              valueFrom: { secretKeyRef: { name: db-credentials, key: POSTGRES_DB } }
            - name: POSTGRES_USER
              valueFrom: { secretKeyRef: { name: db-credentials, key: POSTGRES_USER } }
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: db-credentials, key: POSTGRES_PASSWORD } }
            - name: EMBEDDING_MODEL_NAME
              valueFrom: { configMapKeyRef: { name: ai-config, key: model_name } }
            - name: DATABASE_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@db-service:5432/$(POSTGRES_DB)"
            - name: SQL_SEARCH_FILE
              value: "/app/src/sql/vector_search.sql"
          volumeMounts:
            - name: app-source
              mountPath: /app/src
      volumes:
        - name: app-source
          hostPath:
            path: /run/desktop/mnt/host/g/Learning/IA/IA_Agente_FastAPI/src