apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  # ATENÇÃO: Insira aqui os resultados do Passo 1
  POSTGRES_USER: ZGJh
  POSTGRES_PASSWORD: bjB2aWRhZGU=
  POSTGRES_DB: ZmFzdGFwaQ==